In [1]:
import pandas as pd
import numpy as np

# DATA AQUISITION OF DATASET_1

In [2]:
dataset1=pd.read_csv(r"C:\Users\Lenovo\Desktop\PROJECT 2\dataset_1 - dataset_1.csv")

# Analysing the dataset_1 like shape,unique values, dtypes of columns, and null values.

In [3]:
dataset1.head() ##first 5 rows displayed

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0        1  01-01-2011       1   0     1   0    False        6           1   
1        2  01-01-2011       1   0     1   1    False        6           1   
2        3  01-01-2011       1   0     1   2    False        6           1   
3        4  01-01-2011       1   0     1   3    False        6           1   
4        5  01-01-2011       1   0     1   4    False        6           1   

   temp  
0  0.24  
1  0.22  
2  0.22  
3  0.24  
4  0.24

In [4]:
dataset1 ##all rows in dataset1 displayed

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1  01-01-2011       1   0     1   0    False        6           1   
1          2  01-01-2011       1   0     1   1    False        6           1   
2          3  01-01-2011       1   0     1   2    False        6           1   
3          4  01-01-2011       1   0     1   3    False        6           1   
4          5  01-01-2011       1   0     1   4    False        6           1   
..       ...         ...     ...  ..   ...  ..      ...      ...         ...   
605      606  28-01-2011       1   0     1  11    False        5           3   
606      607  28-01-2011       1   0     1  12    False        5           3   
607      608  28-01-2011       1   0     1  13    False        5           3   
608      609  28-01-2011       1   0     1  14    False        5           3   
609      610  28-01-2011       1   0     1  15    False        5           2   

     temp  
0    0.24  
1    0.22  
2    0.22  
3    0.24  
4    0.24  
..    ...  
605  0.18  
606  0.18  
607  0.18  
608  0.22  
609  0.20  

[610 rows x 10 columns]

In [5]:
dataset1.shape ## shape of the dataset1 is displayed, so it has 610 rows and 10 columns

(610, 10)

In [6]:
dataset1.instant.unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [7]:
dataset1.dteday.unique()

array(['01-01-2011', '02-01-2011', '03-01-2011', '04-01-2011',
       '05-01-2011', '06-01-2011', '07-01-2011', '08-01-2011',
       '09-01-2011', '10-01-2011', '11-01-2011', '12-01-2011',
       '13-01-2011', '14-01-2011', '15-01-2011', '16-01-2011',
       '17-01-2011', '18-01-2011', '19-01-2011', '20-01-2011',
       '21-01-2011', '22-01-2011', '23-01-2011', '24-01-2011',
       '25-01-2011', '26-01-2011', '27-01-2011', '28-01-2011'],
      dtype=object)

In [8]:
dataset1.season.unique()

array([1], dtype=int64)

In [9]:
dataset1.yr.unique()

array([0], dtype=int64)

In [10]:
dataset1.mnth.unique()

array([1], dtype=int64)

In [11]:
dataset1.hr.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int64)

In [12]:
dataset1.holiday.unique()

array([False,  True])

In [13]:
dataset1.weekday.unique()

array([6, 0, 1, 2, 3, 4, 5], dtype=int64)

In [14]:
dataset1.weathersit.unique()

array([1, 2, 3, 4], dtype=int64)

In [15]:
dataset1.temp.unique()

array([0.24, 0.22, 0.2 , 0.32, 0.38, 0.36, 0.42, 0.46, 0.44, 0.4 , 0.34,
       0.3 , 0.26, 0.16, 0.14, 0.18, 0.12, 0.28, 0.1 , 0.08, 0.06, 0.04,
       0.02])

In [16]:
dataset1.isnull().sum() ##checking in how many rows null values are present. It shows that there are no null values in dataset1.

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
dtype: int64

In [17]:
dataset1.info()##displaying just the information of the dataset1 like colum names, null count and datatypes(float, int, bool)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     610 non-null    int64  
 1   dteday      610 non-null    object 
 2   season      610 non-null    int64  
 3   yr          610 non-null    int64  
 4   mnth        610 non-null    int64  
 5   hr          610 non-null    int64  
 6   holiday     610 non-null    bool   
 7   weekday     610 non-null    int64  
 8   weathersit  610 non-null    int64  
 9   temp        610 non-null    float64
dtypes: bool(1), float64(1), int64(7), object(1)
memory usage: 43.6+ KB


# DATA AQUISITION OF DATASET_2

In [18]:
##loaded the dataset_2

dataset2=pd.read_excel(r"C:\Users\Lenovo\Desktop\PROJECT 2\dataset_2.xlsx")

# Analysing the dataset_2 like shape,unique values, dtypes of columns, and null values.

In [19]:
dataset2.head()

Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0           0        1  0.2879  0.81        0.0       3          13   16
1           1        2  0.2727  0.80        0.0       8          32   40
2           2        3  0.2727  0.80        0.0       5          27   32
3           3        4  0.2879  0.75        0.0       3          10   13
4           4        5  0.2879  0.75        0.0       0           1    1

In [20]:
dataset2 ##all rows in dataset2 displayed

Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0             0        1  0.2879  0.81     0.0000       3          13   16
1             1        2  0.2727  0.80     0.0000       8          32   40
2             2        3  0.2727  0.80     0.0000       5          27   32
3             3        4  0.2879  0.75     0.0000       3          10   13
4             4        5  0.2879  0.75     0.0000       0           1    1
..          ...      ...     ...   ...        ...     ...         ...  ...
605         605      606  0.2121  0.93     0.1045       0          30   30
606         606      607  0.2121  0.93     0.1045       1          28   29
607         607      608  0.2121  0.93     0.1045       0          31   31
608         608      609  0.2727  0.80     0.0000       2          36   38
609         609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 8 columns]

In [21]:
dataset2.shape ## shape of the dataset2 is displayed, so it has 610 rows and 10 columns

(610, 8)

In [22]:
dataset2.instant.unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [23]:
dataset2.atemp.unique()

array([0.2879, 0.2727, 0.2576,    nan, 0.3485, 0.3939, 0.3333, 0.4242,
       0.4545, 0.4394, 0.4091, 0.2273, 0.2121, 0.197 , 0.1364, 0.1061,
       0.1212, 0.1667, 0.1818, 0.2424, 0.1515, 0.3182, 0.0606, 0.0758,
       0.0909, 0.303 , 0.0303, 0.0455, 0.    , 0.0152])

In [24]:
dataset2.hum.unique()

array([0.81, 0.8 , 0.75, 0.86, 0.76, 0.77, 0.72, 0.82, 0.88, 0.87, 0.94,
       1.  , 0.71, 0.66, 0.57, 0.46, 0.42, 0.39, 0.44, 0.47, 0.5 , 0.43,
       0.4 , 0.35, 0.3 , 0.32, 0.64, 0.69, 0.55, 0.59, 0.63, 0.68, 0.74,
       0.51, 0.56, 0.52, 0.49, 0.48, 0.37, 0.33, 0.28, 0.38, 0.36, 0.93,
       0.29, 0.53, 0.34, 0.54, 0.41, 0.45, 0.92, 0.62, 0.58, 0.61, 0.6 ,
       0.65, 0.7 , 0.27, 0.21, 0.25, 0.26])

In [25]:
dataset2.windspeed.unique()

array([0.    , 0.0896, 0.2537, 0.2836, 0.2985, 0.194 , 0.2239, 0.1343,
       0.1642, 0.3284, 0.4478, 0.3582, 0.4179, 0.3881, 0.1045, 0.4925,
       0.5522, 0.4627, 0.5224, 0.5821])

In [26]:
dataset2.casual.unique()

array([ 3,  8,  5,  0,  2,  1, 12, 26, 29, 47, 35, 40, 41, 15,  9,  6, 11,
        4,  7, 16, 20, 19, 10, 13, 14, 18, 17, 21, 33, 23, 22, 24],
      dtype=int64)

In [27]:
dataset2.registered.unique()

array([ 13,  32,  27,  10,   1,   0,   2,   7,   6,  24,  30,  55,  47,
        71,  70,  52,  26,  31,  25,  17,  16,   8,   4,  19,  46,  54,
        73,  64,  67,  58,  43,  29,  20,   9,   5,   3,  63, 153,  81,
        33,  41,  48,  53,  66, 146, 148, 102,  49,  11,  36,  92, 177,
        98,  37,  50,  79,  68, 202, 179, 110,  34,  87, 192, 109,  74,
        65,  85, 186, 166, 127,  82,  40,  18,  95, 216, 116,  42,  57,
        78,  59, 163, 158,  51,  76, 190, 125, 178,  39,  14,  15,  56,
        60,  90,  83,  69,  28,  35,  22,  12,  77,  44,  38,  75, 184,
       174, 154,  97, 214,  45,  72, 130,  94, 139, 135, 197, 137, 141,
       156, 117, 155, 134,  89,  80, 108,  61, 124, 132, 196, 107, 100,
       247, 140,  86,  62, 207, 210, 159, 151, 119,  93,  23, 171, 145,
       101,  21, 103, 233, 208, 218, 133], dtype=int64)

In [28]:
dataset2.cnt.unique()

array([ 16,  40,  32,  13,   1,   2,   3,   8,  14,  36,  56,  84,  94,
       106, 110,  93,  67,  35,  37,  34,  28,  39,  17,   9,   6,  20,
        53,  70,  75,  59,  74,  76,  65,  30,  22,  31,   5,  64, 154,
        88,  44,  51,  61,  77,  72, 157,  52,  12,   4, 179, 100,  42,
        57,  78,  97,  63,  83, 212, 182, 112,  54,  48,  11,  33, 195,
       115,  46,  79,  71,  62,  89, 190, 169, 132,  43,  19,  95, 219,
       122,  45,  86, 172, 163,  69,  23,   7, 210, 134,  73,  50,  87,
       187, 123,  15,  25,  98, 102,  55,  10,  49,  82,  92,  41,  38,
       188,  47, 178, 155,  24,  18,  27,  99, 217, 130, 136,  29, 128,
        81,  68, 139, 137, 202,  60, 162, 144, 158, 117,  90, 159, 101,
       118, 129,  26, 104,  91, 113, 105,  21,  80, 125, 133, 197, 109,
       161, 249, 143, 215, 185, 152, 126, 166, 120,  96, 103,  58, 116,
       177, 184, 153, 108, 238, 222, 225, 146, 119], dtype=int64)

In [29]:
dataset2.isnull().sum()

##checking in how many rows null values are present. It shows that there are 11 null values in dataset2 in the column atemp.

Unnamed: 0     0
instant        0
atemp         11
hum            0
windspeed      0
casual         0
registered     0
cnt            0
dtype: int64

In [30]:
dataset2.info()##displaying just the information of the dataset2 like colum names, null count and datatypes(float, int, bool)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  610 non-null    int64  
 1   instant     610 non-null    int64  
 2   atemp       599 non-null    float64
 3   hum         610 non-null    float64
 4   windspeed   610 non-null    float64
 5   casual      610 non-null    int64  
 6   registered  610 non-null    int64  
 7   cnt         610 non-null    int64  
dtypes: float64(3), int64(5)
memory usage: 38.3 KB


In [31]:
## By the above information on dataset2, we can see a column named 'UNNAMED' that is not useful for any analysis.
##So, i am dropping the column named 'UNNAMED' from dataset2.

dataset2=dataset2.drop(['Unnamed: 0'], axis=1)

In [32]:
## Now let's check whether the 'UNNAMED:0' Column is dropped or not.

dataset2.head()

##with the below output we can see the column is dropped.

instant   atemp   hum  windspeed  casual  registered  cnt
0        1  0.2879  0.81        0.0       3          13   16
1        2  0.2727  0.80        0.0       8          32   40
2        3  0.2727  0.80        0.0       5          27   32
3        4  0.2879  0.75        0.0       3          10   13
4        5  0.2879  0.75        0.0       0           1    1

# TREATING THE NULL VALUES AND CENTRAL TENDENCY

In [33]:
dataset2.isnull().sum()

##checking in how many rows null values are present. It shows that there are 11 null values in dataset2 in the column atemp.

instant        0
atemp         11
hum            0
windspeed      0
casual         0
registered     0
cnt            0
dtype: int64

In [34]:
## with the above output we can see that 'atemp' column has got 11 null values.
## so we are going to treat the null values by filling it with the mean value as it the dtype of the 'atemp' column is float.

mean_value=dataset2['atemp'].mean()
dataset2['atemp'].fillna(mean_value, inplace=True)

In [35]:
## Now lets check the null values are filled are not by executing the null value code again.

dataset2.isnull().sum()

##with the below output we found out the null values are treated by adding the mean value of "atemp' column.

instant       0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

# MERGING OF DATASET1 AND DATASET2

In [37]:
dataset1_dataset2=pd.merge(dataset1, dataset2, on='instant', how='inner')

In [38]:
dataset1_dataset2

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1  01-01-2011       1   0     1   0    False        6           1   
1          2  01-01-2011       1   0     1   1    False        6           1   
2          3  01-01-2011       1   0     1   2    False        6           1   
3          4  01-01-2011       1   0     1   3    False        6           1   
4          5  01-01-2011       1   0     1   4    False        6           1   
..       ...         ...     ...  ..   ...  ..      ...      ...         ...   
605      606  28-01-2011       1   0     1  11    False        5           3   
606      607  28-01-2011       1   0     1  12    False        5           3   
607      608  28-01-2011       1   0     1  13    False        5           3   
608      609  28-01-2011       1   0     1  14    False        5           3   
609      610  28-01-2011       1   0     1  15    False        5           2   

     temp   atemp   hum  windspeed  casual  registered  cnt  
0    0.24  0.2879  0.81     0.0000       3          13   16  
1    0.22  0.2727  0.80     0.0000       8          32   40  
2    0.22  0.2727  0.80     0.0000       5          27   32  
3    0.24  0.2879  0.75     0.0000       3          10   13  
4    0.24  0.2879  0.75     0.0000       0           1    1  
..    ...     ...   ...        ...     ...         ...  ...  
605  0.18  0.2121  0.93     0.1045       0          30   30  
606  0.18  0.2121  0.93     0.1045       1          28   29  
607  0.18  0.2121  0.93     0.1045       0          31   31  
608  0.22  0.2727  0.80     0.0000       2          36   38  
609  0.20  0.2576  0.86     0.0000       1          40   41  

[610 rows x 16 columns]

In [39]:
dataset1_dataset2.shape ## shape of the dataset1 is displayed, so it has 610 rows and 10 columns

(610, 16)

In [40]:
dataset1_dataset2.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64